apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: downloader-sloniara-bot
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '60'
    argocd-image-updater.argoproj.io/image-list: bot=harbor.api-api-api.com/downloader-sloniara-bot/bot
    argocd-image-updater.argoproj.io/bot.allow-tags: regexp:^main-[0-9]+-[a-f0-9]{40}$
    argocd-image-updater.argoproj.io/bot.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization:./apps/downloader-sloniara-bot
spec:
  project: gitops-apps
  source:
    repoURL: https://github.com/anomaly51/workload-1-k3s-argocd.git
    targetRevision: main
    path: apps/downloader-sloniara-bot
  destination:
    server: https://kubernetes.default.svc
    namespace: downloader-sloniara-bot
  ignoreDifferences:
  - group: external-secrets.io
    kind: ExternalSecret
    jsonPointers:
    - "/spec/target/deletionPolicy"
    - "/spec/data/0/remoteRef/conversionStrategy"
    - "/spec/data/0/remoteRef/decodingStrategy"
    - "/spec/data/0/remoteRef/metadataPolicy"
    - "/spec/data/0/remoteRef/nullBytePolicy"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
