apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shisha-guid
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '60'
    argocd-image-updater.argoproj.io/image-list: backend=harbor.api-api-api.com/shisha/backend
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^main-[0-9]+-[a-f0-9]{40}$
    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/values/shisha-guid.yaml
    argocd-image-updater.argoproj.io/backend.helm.image-name: images.backend.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: images.backend.tag
spec:
  project: gitops-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: shisha-guid
  ignoreDifferences:
  - group: external-secrets.io
    kind: ExternalSecret
    jsonPointers:
    - "/spec/target/deletionPolicy"
    - "/spec/data/0/remoteRef/conversionStrategy"
    - "/spec/data/0/remoteRef/decodingStrategy"
    - "/spec/data/0/remoteRef/metadataPolicy"
    - "/spec/data/0/remoteRef/nullBytePolicy"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
  sources:
  - repoURL: harbor.api-api-api.com/helm-charts
    chart: common-app
    targetRevision: 0.1.0
    helm:
      releaseName: shisha-guid
      valueFiles:
      - "$values/values/shisha-guid.yaml"
  - repoURL: https://github.com/anomaly51/workload-1-k3s-argocd.git
    targetRevision: main
    ref: values
