apiVersion: v2
name: nfs-provisioner
version: 0.1.0
type: application
dependencies:
- name: nfs-provisioner
  version: 0.1.0
  repository: oci://harbor.api-api-api.com/helm-charts
  alias: platform-nfs-provisioner
