apiVersion: v2
name: vault-store
version: 0.1.0
type: application
dependencies:
- name: vault-store
  version: 0.1.0
  repository: oci://harbor.api-api-api.com/helm-charts
  alias: platform-vault-store
