  apiVersion: argocd-image-updater.argoproj.io/v1alpha1
  kind: ImageUpdater
  metadata:
    name: workload-1-app-images
    namespace: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "2"
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  spec:
    commonUpdateSettings:
      updateStrategy: newest-build
      allowTags: regexp:^main-[0-9]+-[a-f0-9]{40}$
      ignoreTags:
        - latest
        - dev
        - test
      pullSecret: pullsecret:argocd/harbor-pull-secret
    writeBackConfig:
      method: git
      gitConfig:
        repository: https://github.com/anomaly51/workload-1-k3s-argocd.git
        branch: main
    applicationRefs:
    - namePattern: online-shop
      writeBackConfig:
        method: git
        gitConfig:
          repository: https://github.com/anomaly51/workload-1-k3s-argocd.git
          branch: main
          writeBackTarget: kustomization:./apps/online-shop
      images:
- alias: backend
  imageName: harbor.api-api-api.com/online-shop/backend:main-20-5829f3893cf4d511ca320ab50306f348707db04d
  manifestTargets:
    kustomize:
      name: harbor.api-api-api.com/online-shop/backend
    - namePattern: online-shop-frontend
      writeBackConfig:
        method: git
        gitConfig:
          repository: https://github.com/anomaly51/workload-1-k3s-argocd.git
          branch: main
          writeBackTarget: kustomization:./apps/online-shop-frontend
      images:
- alias: frontend
  imageName: harbor.api-api-api.com/online-shop/frontend:main-43-9603db6013888a55d6866bb60e5956e1248cff73
  manifestTargets:
    kustomize:
      name: harbor.api-api-api.com/online-shop/frontend
    - namePattern: shisha-guid
      writeBackConfig:
        method: git
        gitConfig:
          repository: https://github.com/anomaly51/workload-1-k3s-argocd.git
          branch: main
          writeBackTarget: kustomization:./apps/shisha-guid
      images:
- alias: backend
  imageName: harbor.api-api-api.com/shisha/backend:main-42-e9a41fe04e091527ad141b07d4aa74199992c456
  manifestTargets:
    kustomize:
      name: harbor.api-api-api.com/shisha/backend
    - namePattern: shisha-frontend
      writeBackConfig:
        method: git
        gitConfig:
          repository: https://github.com/anomaly51/workload-1-k3s-argocd.git
          branch: main
          writeBackTarget: kustomization:./apps/shisha-frontend
      images:
- alias: frontend
  imageName: harbor.api-api-api.com/shisha/frontend:main-86-997fdfb26e261ecdd7cec344e5d8fe0028d88dab
  manifestTargets:
    kustomize:
      name: harbor.api-api-api.com/shisha/frontend
