apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://github.com/argoproj-labs/argocd-image-updater/config/default?ref=stable
  - harbor-pull-secret.yaml
  - image-updater.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-image-updater-config
    patch: |-
      - op: add
        path: /data
        value:
          argocd.namespace: argocd
          interval: 2m
          log.level: info
          git.user: argocd-image-updater
          git.email: argocd-image-updater@anomaly51.local
          kube.events: "true"
          registries.conf: |
            registries:
              - name: Harbor
                api_url: https://harbor.api-api-api.com
                prefix: harbor.api-api-api.com
                ping: yes
                credentials: pullsecret:argocd/harbor-pull-secret
