replicaCount: 2

image:
  repository: cloudflare/cloudflared
  tag: 2026.5.0

metrics: 0.0.0.0:2000
noAutoupdate: true
defaultService: https://traefik.kube-system.svc.cluster.local:443

tunnel:
  id: bfaa4824-dabf-4534-8b2a-0cfa730ec2f1
  target: bfaa4824-dabf-4534-8b2a-0cfa730ec2f1.cfargotunnel.com

credentials:
  vaultKey: workload-1/cloudflared

argocd:
  enabled: true
  hostname: argocd-workload-1.api-api-api.com
  tlsSecretName: argocd-api-tls-secret

routes:
  - hostname: argocd-utility.api-api-api.com
    service: https://192.168.1.108
  - hostname: vault.api-api-api.com
    service: https://192.168.1.108
  - hostname: harbor.api-api-api.com
    service: https://192.168.1.108
  - hostname: argo-workflows.api-api-api.com
    service: https://192.168.1.108
  - hostname: prometheus.api-api-api.com
    service: https://192.168.1.108
  - hostname: grafana.api-api-api.com
    service: https://192.168.1.108
  - hostname: loki.api-api-api.com
    service: https://192.168.1.108
  - hostname: argocd-workload-1.api-api-api.com
  - hostname: shisha-guid.api-api-api.com
  - hostname: shisha-guid-api.api-api-api.com
  - hostname: online-shop.api-api-api.com
  - hostname: online-shop-api.api-api-api.com
  - hostname: hermes-agent.api-api-api.com
  - hostname: obsidian-livesync.api-api-api.com
  - hostname: architect-business-bot.api-api-api.com
  - hostname: pets-void.api-api-api.com
  - hostname: pingme-backend.api-api-api.com
  - hostname: uptime-monitor.api-api-api.com

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi
