apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - minio.yaml
  - backend.yaml

images:
  - name: harbor.api-api-api.com/shisha/backend
    newTag: main-42-e9a41fe04e091527ad141b07d4aa74199992c456
