apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - harbor-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: harbor.api-api-api.com/shisha/frontend
    newTag: main-86-997fdfb26e261ecdd7cec344e5d8fe0028d88dab
