app:
  namespace:
    create: true
    name: shisha-frontend
    annotations:
      argocd.argoproj.io/sync-options: Delete=false,Prune=false
  image:
    repository: harbor.api-api-api.com/shisha/frontend
    tag: sha-577f47abfaff
  registryPullSecret:
    enabled: true
  selectorLabels:
    app: shisha-frontend
  ports:
  - name: http
    containerPort: 80
  service:
    enabled: true
    port: 80
    targetPort: 80
  ingress:
    enabled: true
    host: shisha-guid.api-api-api.com
