app:
  name: online-shop-frontend
  resourceName: online-shop-frontend
  namespace:
    create: true
    name: online-shop-frontend
  image:
    repository: harbor.api-api-api.com/online-shop/frontend
    tag: sha-1a686126c695
  registryPullSecret:
    enabled: true
  selectorLabels:
    app: online-shop-frontend
  ports:
  - name: http
    containerPort: 80
  service:
    enabled: true
    port: 80
    targetPort: 80
  ingress:
    enabled: true
    host: online-shop.api-api-api.com
    tlsSecretName: online-shop-frontend-tls
