---
app:
  nameOverride: online-shop-frontend
  fullnameOverride: online-shop-frontend

  namespace:
    create: true
    name: online-shop-frontend

  image:
    repository: harbor.api-api-api.com/online-shop/frontend
    tag: main-43-9603db6013888a55d6866bb60e5956e1248cff73

  selectorLabels:
    app: online-shop-frontend

  ports:
    - name: http
      containerPort: 80

  service:
    enabled: true
    port: 80
    targetPort: 80

  registryPullSecret:
    enabled: true

  ingress:
    enabled: true
    host: online-shop.api-api-api.com
    tlsSecretName: online-shop-frontend-tls
