apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: utility-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  generators:
  - git:
      repoURL: https://github.com/anomaly51/workload-1-k3s-argocd.git
      revision: main
      files:
      - path: utility-apps/*/Chart.yaml
  template:
    metadata:
      name: "{{ .name }}"
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: '{{ if or (eq .name "cert-manager") (eq .name "external-secrets") (eq .name "nfs-provisioner") }}10{{ else if eq .name "vault-store" }}20{{ else if eq .name "cert-manager-issuers" }}30{{ else if eq .name "argocd-registry-access" }}35{{ else if or (eq .name "cloudflared") (eq .name "external-dns") }}40{{ else if or (eq .name "harbor") (eq .name "prometheus") (eq .name "vault") }}50{{ else if or (eq .name "architect-business-bot-logs") (eq .name "arc-controller") (eq .name "grafana") (eq .name "loki") }}55{{ else if eq .name "arc-runner-set" }}56{{ else }}60{{ end }}'
    spec:
      project: gitops-apps
      source:
        repoURL: https://github.com/anomaly51/workload-1-k3s-argocd.git
        targetRevision: main
        path: "{{ .path.path }}"
        helm:
          releaseName: "{{ .name }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ if eq .name "argocd-registry-access" }}argocd{{ else if eq .name "arc-controller" }}arc-systems{{ else if eq .name "arc-runner-set" }}arc-runners{{ else if eq .name "architect-business-bot-logs" }}alloy{{ else if or (eq .name "cert-manager") (eq .name "cert-manager-issuers") }}cert-manager{{ else if eq .name "external-dns" }}external-dns{{ else if or (eq .name "external-secrets") (eq .name "vault-store") }}external-secrets{{ else if eq .name "harbor" }}harbor-system{{ else if eq .name "nfs-provisioner" }}nfs-system{{ else }}{{ .name }}{{ end }}'
      ignoreDifferences:
      - group: external-secrets.io
        kind: ExternalSecret
        jsonPointers:
        - "/spec/target/deletionPolicy"
        - "/spec/data/0/remoteRef/conversionStrategy"
        - "/spec/data/0/remoteRef/decodingStrategy"
        - "/spec/data/0/remoteRef/metadataPolicy"
        - "/spec/data/0/remoteRef/nullBytePolicy"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - SkipDryRunOnMissingResource=true
