nfs-subdir-external-provisioner:
  nfs:
    server: 192.168.1.13
    path: "/export/test"
  storageClass:
    name: nfs-client
    provisionerName: cluster.local/nfs-subdir-external-provisioner
    defaultClass: true
    archiveOnDelete: false
    reclaimPolicy: Delete
