apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cert-manager-issuers
  - cloudflared
  - external-dns
  - external-secrets
  - nfs-provisioner
  - prometheus
  - vault-store
