apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - minio.yaml
  - backend.yaml

images:
  - name: harbor.api-api-api.com/online-shop/backend
    newTag: main-20-5829f3893cf4d511ca320ab50306f348707db04d
