external-dns:
  provider:
    name: cloudflare
  env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token
  extraArgs:
  - --cloudflare-proxied
  domainFilters:
  - api-api-api.com
  txtOwnerId: workload-1-k3s
  sources:
  - ingress
  policy: sync
