prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: false
    retention: 6h
    remoteWrite:
    - url: https://prometheus.api-api-api.com/api/v1/write
  scrapeConfigs:
    prometheus:
      metric_relabel_configs:
      - target_label: cluster
        replacement: workload-1-k3s
    kubernetes-api-servers:
      metric_relabel_configs:
      - target_label: cluster
        replacement: workload-1-k3s
    kubernetes-nodes:
      metric_relabel_configs:
      - target_label: cluster
        replacement: workload-1-k3s
    kubernetes-nodes-cadvisor:
      metric_relabel_configs:
      - target_label: cluster
        replacement: workload-1-k3s
    kubernetes-service-endpoints:
      metric_relabel_configs:
      - target_label: cluster
        replacement: workload-1-k3s
    kubernetes-service-endpoints-slow:
      metric_relabel_configs:
      - target_label: cluster
        replacement: workload-1-k3s
    kubernetes-services:
      metric_relabel_configs:
      - target_label: cluster
        replacement: workload-1-k3s
    kubernetes-pods:
      metric_relabel_configs:
      - target_label: cluster
        replacement: workload-1-k3s
    kubernetes-pods-slow:
      metric_relabel_configs:
      - target_label: cluster
        replacement: workload-1-k3s
