{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ default (include "common-app.namespace" $) .namespace }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ default "5m" .refreshInterval | quote }}
  secretStoreRef:
    name: {{ default "vault-backend" .secretStoreRef.name }}
    kind: {{ default "ClusterSecretStore" .secretStoreRef.kind }}
  target:
    name: {{ default .name .targetName }}
    creationPolicy: {{ default "Owner" .creationPolicy }}
    {{- with .template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
