{{- if and .Values.ingress.enabled .Values.image.repository (not .Values.rawManifests) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common-app.fullname" . }}
  namespace: {{ include "common-app.namespace" . }}
  labels:
    {{- include "common-app.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- with .Values.ingress.host }}
  {{- $_ := set $annotations "external-dns.alpha.kubernetes.io/hostname" . }}
  {{- end }}
  {{- with .Values.cluster.externalDns.target }}
  {{- $_ := set $annotations "external-dns.alpha.kubernetes.io/target" . }}
  {{- end }}
  {{- $annotations = mergeOverwrite $annotations .Values.ingress.annotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ default (printf "%s-tls" (include "common-app.fullname" .)) .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "common-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
