{{- with .Values.rawManifests }}
{{- $raw := . }}
{{- range $name, $image := $.Values.images }}
{{- $raw = replace (printf "__IMAGE_%s__" $name) (printf "%s:%s" $image.repository $image.tag) $raw }}
{{- end }}
{{- range $rawObject := splitList "\n---" $raw }}
{{- $rawObject = trim $rawObject }}
{{- if $rawObject }}
---
{{- $renderObject := fromYaml $rawObject }}
{{- if eq (get $renderObject "kind") "Ingress" }}
{{- $metadata := get $renderObject "metadata" | default dict }}
{{- $annotations := get $metadata "annotations" | default dict }}
{{- $spec := get $renderObject "spec" | default dict }}
{{- $hosts := list }}
{{- range (get $spec "rules" | default list) }}
{{- with .host }}
{{- $hosts = append $hosts . }}
{{- end }}
{{- end }}
{{- if and $hosts (not (hasKey $annotations "external-dns.alpha.kubernetes.io/hostname")) }}
{{- $_ := set $annotations "external-dns.alpha.kubernetes.io/hostname" ($hosts | uniq | join ",") }}
{{- end }}
{{- with $.Values.cluster.externalDns.target }}
{{- if not (hasKey $annotations "external-dns.alpha.kubernetes.io/target") }}
{{- $_ := set $annotations "external-dns.alpha.kubernetes.io/target" . }}
{{- end }}
{{- end }}
{{- $_ := set $metadata "annotations" $annotations }}
{{- $_ := set $renderObject "metadata" $metadata }}
{{- end }}
{{ toYaml $renderObject }}
{{- end }}
{{- end }}
{{- end }}
